"""Peripheral_IC v3 timing-only row-parallel behavioral model."""

from .peripheral_ic_v3_behavioral import (
    COLS,
    ROWS,
    WORD_MASK,
    DeviceReadModel,
    EnergyModel,
    EnergyModelV3,
    OperationReport,
    PeripheralICV3Behavioral,
    SenseMarginModelV3,
    SearchHit,
    SearchReport,
    TimingModel,
    TimingModelV3,
    bits_to_word,
    decode_rows_from_d_pins,
    encode_d_pins_for_row,
    normalize_mask,
    normalize_word,
    word_to_bits,
)

__all__ = [
    "COLS",
    "ROWS",
    "WORD_MASK",
    "DeviceReadModel",
    "EnergyModel",
    "EnergyModelV3",
    "OperationReport",
    "PeripheralICV3Behavioral",
    "SenseMarginModelV3",
    "SearchHit",
    "SearchReport",
    "TimingModel",
    "TimingModelV3",
    "bits_to_word",
    "decode_rows_from_d_pins",
    "encode_d_pins_for_row",
    "normalize_mask",
    "normalize_word",
    "word_to_bits",
]
